language: python
env:
  - TOXENV=flake8
  - TOXENV=py26-crypto
  - TOXENV=py27-crypto
  - TOXENV=py32-crypto
  - TOXENV=py33-crypto
  - TOXENV=py34-crypto
  - TOXENV=py34-nocrypto
  - TOXENV=py27-nocrypto
  - TOXENV=py34-contrib_crypto
  - TOXENV=py27-contrib_crypto
install:
  - pip install -U pip
  - pip install -U tox coveralls
script:
  - tox
after_success:
  - coveralls
