language: python
python:
  - "3.6"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5 python3.5-dev
sudo: false
env:
  - TOXENV=flake8
  - TOXENV=py27-crypto
  - TOXENV=py34-crypto
  - TOXENV=py35-crypto
  - TOXENV=py36-crypto
  - TOXENV=py34-nocrypto
  - TOXENV=py35-nocrypto
  - TOXENV=py36-nocrypto
  - TOXENV=py27-nocrypto
  - TOXENV=py35-contrib_crypto
  - TOXENV=py36-contrib_crypto
  - TOXENV=py27-contrib_crypto
  
install:
  - pip install -U pip
  - pip install -U tox coveralls
script:
  - tox
after_success:
  - coveralls
